apiVersion: v1
kind: ConfigMap
metadata:
  name: exoper-tenant-service-config
  namespace: exoper-system
  labels:
    app.kubernetes.io/name: exoper-tenant-service
    app.kubernetes.io/component: tenant
    app.kubernetes.io/version: "1.0.0"
data:
  tenant.yaml: |
    server:
      name: "exoper-tenant-service"
      version: "1.0.0"
      environment: "production"
      host: "0.0.0.0"
      port: 8082
      grpc_port: 9092
      read_timeout: "30s"
      write_timeout: "30s"
      idle_timeout: "300s"
      shutdown_timeout: "60s"

    security:
      tls:
        enabled: true
        cert_file: "/etc/ssl/certs/tls.crt"
        key_file: "/etc/ssl/private/tls.key"
        ca_file: "/etc/ssl/certs/ca.crt"
        min_version: "1.3"
      mtls:
        enabled: true
        client_ca_file: "/etc/ssl/certs/client-ca.crt"
        verify_client_cert: true

    tenant:
      isolation:
        enabled: true
        strategy: "namespace"
        encryption_per_tenant: true
        data_residency: true
      
      limits:
        max_users_per_tenant: 10000
        max_requests_per_second: 1000
        max_storage_gb: 1000
        max_ai_models: 50
      
      billing:
        enabled: true
        metering_interval: "1h"
        usage_tracking: true
        cost_allocation: true

    database:
      driver: "postgres"
      port: 5432
      ssl_mode: "require"
      max_open_conns: 100
      max_idle_conns: 25
      conn_max_lifetime: "5m"
      tenant_isolation: "schema"

    redis:
      enabled: true
      port: 6380
      db: 2
      pool_size: 50
      tenant_prefix: "tenant:"
      config_prefix: "tenant:config:"
      tls_enabled: true

    observability:
      logging:
        level: "info"
        format: "json"
        output: "stdout"
        tenant_context: true
      tracing:
        enabled: true
        service_name: "exoper-tenant-service"
        jaeger:
          endpoint: "http://jaeger-collector.observability.svc.cluster.local:14268/api/traces"
      metrics:
        enabled: true
        prometheus:
          enabled: true
          path: "/metrics"
          port: 8083
        tenant_metrics: true

    compliance:
      enabled: true
      data_classification: true
      gdpr_compliance: true
      data_retention_policies: true
      audit_tenant_operations: true

    rate_limiting:
      enabled: true
      per_tenant:
        requests_per_minute: 100
        burst: 200
      admin_operations:
        requests_per_minute: 10
        burst: 20

    health_check:
      enabled: true
      path: "/health"
      interval: "15s"
      timeout: "5s"
