apiVersion: v1
kind: Secret
metadata:
  name: exoper-tenant-service-secrets
  namespace: exoper-system
  labels:
    app.kubernetes.io/name: exoper-tenant-service
    app.kubernetes.io/component: tenant
    app.kubernetes.io/version: "1.0.0"
type: Opaque
data:
  # Base64 encoded secrets - replace with actual values
  tenant-db-password: "Y2hhbmdlLW1lLWluLXByb2R1Y3Rpb24="
  redis-password: "Y2hhbmdlLW1lLWluLXByb2R1Y3Rpb24="
  tenant-encryption-key: "Y2hhbmdlLW1lLWluLXByb2R1Y3Rpb24="
  billing-api-key: "Y2hhbmdlLW1lLWluLXByb2R1Y3Rpb24="
  compliance-encryption-key: "Y2hhbmdlLW1lLWluLXByb2R1Y3Rpb24="
---
apiVersion: v1
kind: Secret
metadata:
  name: exoper-tenant-service-tls
  namespace: exoper-system
  labels:
    app.kubernetes.io/name: exoper-tenant-service
    app.kubernetes.io/component: tenant
type: kubernetes.io/tls
data:
  # Base64 encoded TLS certificate and key
  tls.crt: LS0tLS1CRUdJTi... # Replace with actual certificate
  tls.key: LS0tLS1CRUdJTi... # Replace with actual private key
  ca.crt: LS0tLS1CRUdJTi...  # Replace with actual CA certificate
