apiVersion: v1
kind: ConfigMap
metadata:
  name: exoper-auth-service-config
  namespace: exoper-system
  labels:
    app.kubernetes.io/name: exoper-auth-service
    app.kubernetes.io/component: auth
    app.kubernetes.io/version: "1.0.0"
data:
  auth.yaml: |
    server:
      name: "exoper-auth-service"
      version: "1.0.0"
      environment: "production"
      host: "0.0.0.0"
      port: 8081
      grpc_port: 9091
      read_timeout: "30s"
      write_timeout: "30s"
      idle_timeout: "300s"
      shutdown_timeout: "60s"

    security:
      tls:
        enabled: true
        cert_file: "/etc/ssl/certs/tls.crt"
        key_file: "/etc/ssl/private/tls.key"
        ca_file: "/etc/ssl/certs/ca.crt"
        min_version: "1.3"
      mtls:
        enabled: true
        client_ca_file: "/etc/ssl/certs/client-ca.crt"
        verify_client_cert: true

    auth:
      jwt:
        issuer: "exoper-auth-production"
        audience: "exoper-platform"
        access_token_expiry: "15m"
        refresh_token_expiry: "8h"
        algorithm: "RS256"
        private_key_file: "/etc/ssl/private/jwt-signing.key"
        public_key_file: "/etc/ssl/certs/jwt-signing.crt"
      
      providers:
        local:
          enabled: true
          password_min_length: 16
          password_complexity: true
          max_login_attempts: 3
          lockout_duration: "60m"
          require_mfa: true
        
        oidc:
          enabled: true
          providers:
            - name: "azure_ad"
              scopes: ["openid", "profile", "email"]
            - name: "google"
              discovery_url: "https://accounts.google.com/.well-known/openid_configuration"
              scopes: ["openid", "profile", "email"]

    database:
      driver: "postgres"
      port: 5432
      ssl_mode: "require"
      max_open_conns: 100
      max_idle_conns: 25
      conn_max_lifetime: "5m"

    redis:
      enabled: true
      port: 6380
      db: 1
      pool_size: 50
      session_prefix: "auth:session:"
      blacklist_prefix: "auth:blacklist:"
      tls_enabled: true

    observability:
      logging:
        level: "info"
        format: "json"
        output: "stdout"
        sensitive_fields_redaction: true
      tracing:
        enabled: true
        service_name: "exoper-auth-service"
        jaeger:
          endpoint: "http://jaeger-collector.observability.svc.cluster.local:14268/api/traces"
      metrics:
        enabled: true
        prometheus:
          enabled: true
          path: "/metrics"
          port: 8082

    session:
      store_type: "redis"
      cookie_name: "exoper_session"
      cookie_domain: ".exoper.com"
      cookie_secure: true
      cookie_http_only: true
      cookie_same_site: "strict"
      max_age: 900

    rate_limiting:
      enabled: true
      login_attempts:
        requests_per_minute: 3
        burst: 5
      token_requests:
        requests_per_minute: 10
        burst: 20

    health_check:
      enabled: true
      path: "/health"
      interval: "15s"
      timeout: "5s"
