apiVersion: apps/v1
kind: Deployment
metadata:
  name: exoper-auth-service
  namespace: exoper-system
  labels:
    app.kubernetes.io/name: exoper-auth-service
    app.kubernetes.io/component: auth
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: helm
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: exoper-auth-service
      app.kubernetes.io/component: auth
  template:
    metadata:
      labels:
        app.kubernetes.io/name: exoper-auth-service
        app.kubernetes.io/component: auth
        app.kubernetes.io/version: "1.0.0"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8082"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: exoper-gateway
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: auth-service
        image: exoper/auth-service:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8081
          protocol: TCP
        - name: grpc
          containerPort: 9091
          protocol: TCP
        - name: metrics
          containerPort: 8082
          protocol: TCP
        env:
        - name: CONFIG_PATH
          value: "/etc/config/auth.yaml"
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: exoper-auth-service-secrets
              key: jwt-secret-key
        - name: AUTH_DB_HOST
          value: "postgres-auth.exoper-system.svc.cluster.local"
        - name: AUTH_DB_NAME
          value: "exoper_auth"
        - name: AUTH_DB_USER
          value: "exoper_auth_user"
        - name: AUTH_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: exoper-auth-service-secrets
              key: auth-db-password
        - name: REDIS_HOST
          value: "redis-auth.exoper-system.svc.cluster.local"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: exoper-auth-service-secrets
              key: redis-password
        - name: AZURE_CLIENT_ID
          value: "your-azure-client-id"
        - name: AZURE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: exoper-auth-service-secrets
              key: azure-client-secret
        - name: AZURE_TENANT_ID
          value: "your-azure-tenant-id"
        - name: AZURE_DISCOVERY_URL
          value: "https://login.microsoftonline.com/your-tenant-id/v2.0/.well-known/openid_configuration"
        - name: GOOGLE_CLIENT_ID
          value: "your-google-client-id"
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: exoper-auth-service-secrets
              key: google-client-secret
        - name: MFA_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: exoper-auth-service-secrets
              key: mfa-encryption-key
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
        - name: tls-certs
          mountPath: /etc/ssl/certs
          readOnly: true
        - name: tls-private
          mountPath: /etc/ssl/private
          readOnly: true
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
          capabilities:
            drop:
            - ALL
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8081
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 30
      volumes:
      - name: config
        configMap:
          name: exoper-auth-service-config
      - name: tls-certs
        secret:
          secretName: exoper-auth-service-tls
          items:
          - key: tls.crt
            path: tls.crt
          - key: ca.crt
            path: ca.crt
          - key: tls.crt
            path: client-ca.crt
          - key: jwt-signing.crt
            path: jwt-signing.crt
      - name: tls-private
        secret:
          secretName: exoper-auth-service-tls
          items:
          - key: tls.key
            path: tls.key
          - key: jwt-signing.key
            path: jwt-signing.key
          defaultMode: 0400
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - exoper-auth-service
              topologyKey: kubernetes.io/hostname
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 300
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 300
