apiVersion: v1
kind: Service
metadata:
  name: exoper-auth-service
  namespace: exoper-system
  labels:
    app.kubernetes.io/name: exoper-auth-service
    app.kubernetes.io/component: auth
    app.kubernetes.io/version: "1.0.0"
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 8081
    targetPort: 8081
    protocol: TCP
  - name: grpc
    port: 9091
    targetPort: 9091
    protocol: TCP
  selector:
    app.kubernetes.io/name: exoper-auth-service
    app.kubernetes.io/component: auth
---
apiVersion: v1
kind: Service
metadata:
  name: exoper-auth-service-metrics
  namespace: exoper-system
  labels:
    app.kubernetes.io/name: exoper-auth-service
    app.kubernetes.io/component: auth
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8082"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 8082
    targetPort: 8082
    protocol: TCP
  selector:
    app.kubernetes.io/name: exoper-auth-service
    app.kubernetes.io/component: auth
