# Production Environment - Auth Service Configuration
server:
  name: "exoper-auth-service"
  version: "1.0.0"
  environment: "production"
  host: "0.0.0.0"
  port: 8081
  grpc_port: 9091
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "300s"
  shutdown_timeout: "60s"

security:
  tls:
    enabled: true
    cert_file: "/etc/ssl/certs/auth-service.crt"
    key_file: "/etc/ssl/private/auth-service.key"
    ca_file: "/etc/ssl/certs/ca.crt"
    min_version: "1.3"
    cipher_suites:
      - "TLS_AES_256_GCM_SHA384"
      - "TLS_CHACHA20_POLY1305_SHA256"
      - "TLS_AES_128_GCM_SHA256"
  mtls:
    enabled: true
    client_ca_file: "/etc/ssl/certs/client-ca.crt"
    verify_client_cert: true
    require_and_verify_client_cert: true

auth:
  jwt:
    secret_key: "${JWT_SECRET_KEY}"
    issuer: "exoper-auth-production"
    audience: "exoper-platform"
    access_token_expiry: "15m"
    refresh_token_expiry: "8h"
    algorithm: "RS256"
    private_key_file: "/etc/ssl/private/jwt-signing.key"
    public_key_file: "/etc/ssl/certs/jwt-signing.crt"
    key_rotation_interval: "24h"
  
  providers:
    local:
      enabled: true
      password_min_length: 16
      password_complexity: true
      password_history: 12
      max_login_attempts: 3
      lockout_duration: "60m"
      progressive_lockout: true
      require_mfa: true
    
    oidc:
      enabled: true
      providers:
        - name: "azure_ad"
          client_id: "${AZURE_CLIENT_ID}"
          client_secret: "${AZURE_CLIENT_SECRET}"
          discovery_url: "${AZURE_DISCOVERY_URL}"
          scopes: ["openid", "profile", "email"]
          tenant_id: "${AZURE_TENANT_ID}"
        - name: "google"
          client_id: "${GOOGLE_CLIENT_ID}"
          client_secret: "${GOOGLE_CLIENT_SECRET}"
          discovery_url: "https://accounts.google.com/.well-known/openid_configuration"
          scopes: ["openid", "profile", "email"]
        - name: "okta"
          client_id: "${OKTA_CLIENT_ID}"
          client_secret: "${OKTA_CLIENT_SECRET}"
          discovery_url: "${OKTA_DISCOVERY_URL}"
          scopes: ["openid", "profile", "email", "groups"]

  mfa:
    enabled: true
    providers:
      - "totp"
      - "sms"
      - "email"
    backup_codes:
      enabled: true
      count: 10
    remember_device_duration: "30d"

database:
  driver: "postgres"
  host: "${DB_HOST}"
  port: 5432
  name: "${AUTH_DB_NAME}"
  user: "${AUTH_DB_USER}"
  password: "${AUTH_DB_PASSWORD}"
  ssl_mode: "require"
  ssl_cert: "/etc/ssl/certs/db-client.crt"
  ssl_key: "/etc/ssl/private/db-client.key"
  ssl_root_cert: "/etc/ssl/certs/db-ca.crt"
  max_open_conns: 100
  max_idle_conns: 25
  conn_max_lifetime: "5m"
  encryption_at_rest: true

redis:
  enabled: true
  host: "${REDIS_HOST}"
  port: 6380
  password: "${REDIS_PASSWORD}"
  db: 1
  pool_size: 50
  session_prefix: "auth:session:"
  blacklist_prefix: "auth:blacklist:"
  mfa_prefix: "auth:mfa:"
  tls_enabled: true
  tls_cert_file: "/etc/ssl/certs/redis-client.crt"
  tls_key_file: "/etc/ssl/private/redis-client.key"
  tls_ca_file: "/etc/ssl/certs/redis-ca.crt"

observability:
  logging:
    level: "warn"
    format: "json"
    output: "stdout"
    file_path: "/var/log/exoper/auth-service.log"
    max_size: 500
    max_backups: 10
    max_age: 90
    compress: true
    sensitive_fields_redaction: true
    audit_logging: true
  tracing:
    enabled: true
    service_name: "exoper-auth-service"
    jaeger:
      endpoint: "${JAEGER_ENDPOINT}"
      sampler_type: "probabilistic"
      sampler_param: 0.01
  metrics:
    enabled: true
    prometheus:
      enabled: true
      path: "/metrics"
      port: 8082
      tls_enabled: true

session:
  store_type: "redis"
  cookie_name: "exoper_session"
  cookie_domain: ".exoper.com"
  cookie_secure: true
  cookie_http_only: true
  cookie_same_site: "strict"
  max_age: 900  # 15 minutes
  session_timeout: "15m"
  absolute_timeout: "8h"

rate_limiting:
  enabled: true
  login_attempts:
    requests_per_minute: 3
    burst: 5
    lockout_duration: "60m"
  token_requests:
    requests_per_minute: 10
    burst: 20
  password_reset:
    requests_per_hour: 3
    requests_per_day: 10

security_policies:
  password_policy:
    min_length: 16
    require_uppercase: true
    require_lowercase: true
    require_numbers: true
    require_special_chars: true
    forbidden_patterns:
      - "password"
      - "123456"
      - "qwerty"
    history_count: 12
  
  account_lockout:
    max_failed_attempts: 3
    lockout_duration: "60m"
    progressive_lockout: true
    notify_admin: true
  
  session_security:
    concurrent_sessions_limit: 3
    idle_timeout: "15m"
    absolute_timeout: "8h"
    ip_binding: true
    user_agent_binding: true

compliance:
  enabled: true
  audit_all_auth_events: true
  pii_encryption: true
  gdpr_compliance: true
  data_retention_days: 2555  # 7 years

health_check:
  enabled: true
  path: "/health"
  interval: "15s"
  timeout: "5s"
  dependencies:
    - "database"
    - "redis"
    - "oidc_providers"
