# Staging Environment - Auth Service Configuration
server:
  name: "exoper-auth-service"
  version: "1.0.0"
  environment: "staging"
  host: "0.0.0.0"
  port: 8081
  grpc_port: 9091
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "120s"
  shutdown_timeout: "30s"

security:
  tls:
    enabled: true
    cert_file: "/etc/ssl/certs/auth-service.crt"
    key_file: "/etc/ssl/private/auth-service.key"
    ca_file: "/etc/ssl/certs/ca.crt"
  mtls:
    enabled: true
    client_ca_file: "/etc/ssl/certs/client-ca.crt"
    verify_client_cert: true

auth:
  jwt:
    secret_key: "${JWT_SECRET_KEY}"
    issuer: "exoper-auth-staging"
    audience: "exoper-platform"
    access_token_expiry: "1h"
    refresh_token_expiry: "24h"
    algorithm: "RS256"
    private_key_file: "/etc/ssl/private/jwt-signing.key"
    public_key_file: "/etc/ssl/certs/jwt-signing.crt"
  
  providers:
    local:
      enabled: true
      password_min_length: 12
      password_complexity: true
      max_login_attempts: 3
      lockout_duration: "30m"
    
    oidc:
      enabled: true
      providers:
        - name: "azure_ad"
          client_id: "${AZURE_CLIENT_ID}"
          client_secret: "${AZURE_CLIENT_SECRET}"
          discovery_url: "${AZURE_DISCOVERY_URL}"
          scopes: ["openid", "profile", "email"]
        - name: "google"
          client_id: "${GOOGLE_CLIENT_ID}"
          client_secret: "${GOOGLE_CLIENT_SECRET}"
          discovery_url: "https://accounts.google.com/.well-known/openid_configuration"
          scopes: ["openid", "profile", "email"]

database:
  driver: "postgres"
  host: "${DB_HOST}"
  port: 5432
  name: "${AUTH_DB_NAME}"
  user: "${AUTH_DB_USER}"
  password: "${AUTH_DB_PASSWORD}"
  ssl_mode: "require"
  max_open_conns: 50
  max_idle_conns: 10
  conn_max_lifetime: "5m"

redis:
  enabled: true
  host: "${REDIS_HOST}"
  port: 6379
  password: "${REDIS_PASSWORD}"
  db: 1
  pool_size: 20
  session_prefix: "auth:session:"
  blacklist_prefix: "auth:blacklist:"

observability:
  logging:
    level: "info"
    format: "json"
    output: "stdout"
    file_path: "/var/log/exoper/auth-service.log"
  tracing:
    enabled: true
    service_name: "exoper-auth-service"
    jaeger:
      endpoint: "${JAEGER_ENDPOINT}"
  metrics:
    enabled: true
    prometheus:
      enabled: true
      path: "/metrics"
      port: 8082

session:
  store_type: "redis"
  cookie_name: "exoper_session"
  cookie_domain: ".exoper.com"
  cookie_secure: true
  cookie_http_only: true
  cookie_same_site: "strict"
  max_age: 3600

rate_limiting:
  enabled: true
  login_attempts:
    requests_per_minute: 5
    burst: 10
  token_requests:
    requests_per_minute: 30
    burst: 50

health_check:
  enabled: true
  path: "/health"
  interval: "30s"
  timeout: "10s"
