apiVersion: v1
kind: ConfigMap
metadata:
  name: exoper-gateway-config
  namespace: exoper-system
  labels:
    app.kubernetes.io/name: exoper-gateway
    app.kubernetes.io/component: gateway
    app.kubernetes.io/version: "1.0.0"
data:
  gateway.yaml: |
    server:
      name: "exoper-gateway"
      version: "1.0.0"
      environment: "production"
      host: "0.0.0.0"
      port: 8080
      grpc_port: 9090
      read_timeout: "30s"
      write_timeout: "30s"
      idle_timeout: "300s"
      shutdown_timeout: "60s"
      max_header_bytes: 1048576

    security:
      tls:
        enabled: true
        cert_file: "/etc/ssl/certs/tls.crt"
        key_file: "/etc/ssl/private/tls.key"
        ca_file: "/etc/ssl/certs/ca.crt"
        min_version: "1.3"
      mtls:
        enabled: true
        client_ca_file: "/etc/ssl/certs/client-ca.crt"
        verify_client_cert: true

    observability:
      logging:
        level: "info"
        format: "json"
        output: "stdout"
      tracing:
        enabled: true
        service_name: "exoper-gateway"
        jaeger:
          endpoint: "http://jaeger-collector.observability.svc.cluster.local:14268/api/traces"
      metrics:
        enabled: true
        prometheus:
          enabled: true
          path: "/metrics"
          port: 8081

    services:
      auth_service:
        host: "exoper-auth-service.exoper-system.svc.cluster.local"
        port: 8081
        grpc_port: 9091
        timeout: "5s"
      tenant_service:
        host: "exoper-tenant-service.exoper-system.svc.cluster.local"
        port: 8082
        grpc_port: 9092
        timeout: "5s"

    health_check:
      enabled: true
      path: "/health"
      interval: "15s"
      timeout: "5s"
