apiVersion: v1
kind: Service
metadata:
  name: exoper-gateway
  namespace: exoper-system
  labels:
    app.kubernetes.io/name: exoper-gateway
    app.kubernetes.io/component: gateway
    app.kubernetes.io/version: "1.0.0"
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  type: LoadBalancer
  ports:
  - name: https
    port: 443
    targetPort: 8080
    protocol: TCP
  - name: grpc
    port: 9090
    targetPort: 9090
    protocol: TCP
  selector:
    app.kubernetes.io/name: exoper-gateway
    app.kubernetes.io/component: gateway
---
apiVersion: v1
kind: Service
metadata:
  name: exoper-gateway-metrics
  namespace: exoper-system
  labels:
    app.kubernetes.io/name: exoper-gateway
    app.kubernetes.io/component: gateway
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8081"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app.kubernetes.io/name: exoper-gateway
    app.kubernetes.io/component: gateway
